# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 606)
        MainWindow.setMinimumSize(QtCore.QSize(200, 0))
        MainWindow.setMaximumSize(QtCore.QSize(200, 16777215))
        MainWindow.setTabletTracking(True)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 201, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.layoutWidget)
        self.btnAdd.setEnabled(False)
        self.btnAdd.setMinimumSize(QtCore.QSize(24, 24))
        self.btnAdd.setMaximumSize(QtCore.QSize(24, 24))
        self.btnAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/plus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setAutoDefault(True)
        self.btnAdd.setDefault(True)
        self.btnAdd.setFlat(True)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnDel = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDel.setEnabled(False)
        self.btnDel.setMinimumSize(QtCore.QSize(24, 24))
        self.btnDel.setMaximumSize(QtCore.QSize(24, 24))
        self.btnDel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/minus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDel.setIcon(icon1)
        self.btnDel.setIconSize(QtCore.QSize(16, 16))
        self.btnDel.setAutoRepeatDelay(299)
        self.btnDel.setAutoDefault(False)
        self.btnDel.setDefault(False)
        self.btnDel.setFlat(True)
        self.btnDel.setObjectName("btnDel")
        self.horizontalLayout.addWidget(self.btnDel)
        self.btnGetContacts = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGetContacts.setEnabled(False)
        self.btnGetContacts.setMinimumSize(QtCore.QSize(70, 0))
        self.btnGetContacts.setMaximumSize(QtCore.QSize(100, 20))
        self.btnGetContacts.setFlat(True)
        self.btnGetContacts.setObjectName("btnGetContacts")
        self.horizontalLayout.addWidget(self.btnGetContacts)
        self.lstContacts = QtWidgets.QListWidget(self.centralwidget)
        self.lstContacts.setEnabled(True)
        self.lstContacts.setGeometry(QtCore.QRect(0, 60, 198, 481))
        self.lstContacts.setMinimumSize(QtCore.QSize(198, 0))
        self.lstContacts.setMaximumSize(QtCore.QSize(198, 16777215))
        self.lstContacts.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lstContacts.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lstContacts.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lstContacts.setObjectName("lstContacts")
        self.lnContact = QtWidgets.QLineEdit(self.centralwidget)
        self.lnContact.setEnabled(False)
        self.lnContact.setGeometry(QtCore.QRect(0, 0, 198, 31))
        self.lnContact.setMinimumSize(QtCore.QSize(198, 0))
        self.lnContact.setMaximumSize(QtCore.QSize(198, 16777215))
        self.lnContact.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lnContact.setFrame(False)
        self.lnContact.setObjectName("lnContact")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(0, 540, 200, 41))
        self.btnConnect.setMinimumSize(QtCore.QSize(160, 0))
        self.btnConnect.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnConnect.setAutoDefault(False)
        self.btnConnect.setDefault(False)
        self.btnConnect.setFlat(True)
        self.btnConnect.setObjectName("btnConnect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusMessage = QtWidgets.QStatusBar(MainWindow)
        self.statusMessage.setObjectName("statusMessage")
        MainWindow.setStatusBar(self.statusMessage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Contacts"))
        self.btnGetContacts.setText(_translate("MainWindow", "Get contacts"))
        self.lstContacts.setSortingEnabled(True)
        self.btnConnect.setText(_translate("MainWindow", "Connect"))

import resources_rc
